### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Alejandro-Trave-Generador-Excusas#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- ¡Buen trabajo @Atravep ... ¡Felicidades!
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- ¡Bien resuelto!
- Genial haber añadido la lógica de los iconos. ¡Muy buen trabajo!
- Para seguir practicando JS, te recomiendo duplicar el repositorio y usar el método `.map` para la lógica de tu proyecto.

**Comment by Atravep** [comment]
Gracias! esta tardes podré seguir con la tarea y realizar ese duplicado que me sugieres.
saludos!!
